title: Sumanth Samsani # your name (or website title) here
logo: "/images/IMG_3739.HEIC?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sumanth
  <br><br>
  Samsani 
  <br><br>
  <a href="https://www.linkedin.com/in/sumanthsamsani/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-4V8L5M64XX # your Google Analytics tracking ID here
